{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a5ddab50",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "371e8915",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler, MinMaxScaler\n",
    "\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.naive_bayes import GaussianNB\n",
    "\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "from sklearn.pipeline import Pipeline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "55b002bd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load dataset\n",
    "df = pd.read_csv('data.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "fb1fab97",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Drop rows with missing values\n",
    "df.dropna(subset=['Review text'], inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c9cd6822",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.feature_extraction.text import TfidfVectorizer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "964756f4",
   "metadata": {},
   "outputs": [],
   "source": [
    "vectorizer = TfidfVectorizer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "3492c44a",
   "metadata": {},
   "outputs": [],
   "source": [
    "X = vectorizer.fit_transform(df['Review text'])\n",
    "y = df['Ratings']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9cc7987a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(6382, 3497) (2128, 3497)\n"
     ]
    }
   ],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)\n",
    "\n",
    "print(X_train.shape, X_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "335f4cb1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024/03/27 09:57:11 INFO mlflow.tracking.fluent: Experiment with name 'Sentimental Analysis' does not exist. Creating a new experiment.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Experiment: artifact_location='file:///Users/rameshbabu/MLFlow%20Projects/mlruns/153116874839389910', creation_time=1711513631650, experiment_id='153116874839389910', last_update_time=1711513631650, lifecycle_stage='active', name='Sentimental Analysis', tags={}>"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import mlflow\n",
    "from sklearn.preprocessing import MaxAbsScaler\n",
    "mlflow.set_experiment(\"Sentimental Analysis\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "ff0cc3ce-2a12-4e26-9f6e-b9a1df3a9e2e",
   "metadata": {},
   "outputs": [],
   "source": [
    "pipelines = {\n",
    "    'kneighbors': Pipeline([\n",
    "        ('scaler', MaxAbsScaler()),\n",
    "        ('classifier', KNeighborsClassifier())\n",
    "    ]),\n",
    "    'knn' : Pipeline([\n",
    "        ('scaler', StandardScaler()),\n",
    "        ('classifier', KNeighborsClassifier())\n",
    "    ]), \n",
    "    'svc' : Pipeline([\n",
    "        ('scaler', StandardScaler()),\n",
    "        ('classifier', SVC())\n",
    "    ]),\n",
    "    'logistic_regression': Pipeline([\n",
    "        ('scaler', StandardScaler()),\n",
    "        ('classifier', LogisticRegression())\n",
    "    ]),\n",
    "    'random_forest': Pipeline([\n",
    "        ('scaler', StandardScaler()),\n",
    "        ('classifier', RandomForestClassifier())\n",
    "    ]),\n",
    "    'decision_tree': Pipeline([\n",
    "        ('scaler', StandardScaler()),\n",
    "        ('classifier', DecisionTreeClassifier())\n",
    "    ])\n",
    "}\n",
    "\n",
    "# Define parameter grid for each algorithm\n",
    "param_grids = {\n",
    "    'kneighbors': [\n",
    "        {\n",
    "        'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "        'classifier__n_neighbors' : [i for i in range(3, 21, 2)],              \n",
    "        'classifier__p' : [1, 2, 3]\n",
    "        }\n",
    "    ],\n",
    "    'knn': [\n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__n_neighbors' : [i for i in range(3, 21, 2)], \n",
    "            'classifier__p' : [1, 2, 3]\n",
    "        }\n",
    "    ],\n",
    "    'svc': [\n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__kernel' : ['rbf'], \n",
    "            'classifier__C' : [0.1, 0.01, 1, 10, 100]\n",
    "        }, \n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__kernel' : ['poly'], \n",
    "            'classifier__degree' : [2, 3, 4, 5], \n",
    "            'classifier__C' : [0.1, 0.01, 1, 10, 100]\n",
    "        }, \n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__kernel' : ['linear'], \n",
    "            'classifier__C' : [0.1, 0.01, 1, 10, 100]\n",
    "        }\n",
    "    ],\n",
    "    'logistic_regression': [\n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__C': [0.1, 1, 10], \n",
    "            'classifier__penalty': ['l2']\n",
    "        }, \n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__C': [0.1, 1, 10], \n",
    "            'classifier__penalty': ['l1'], \n",
    "            'classifier__solver': ['liblinear']\n",
    "        }, \n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__C': [0.1, 1, 10], \n",
    "            'classifier__penalty': ['elasticnet'], \n",
    "            'classifier__l1_ratio': [0.4, 0.5, 0.6],\n",
    "            'classifier__solver': ['saga']\n",
    "        }\n",
    "    ],\n",
    "    'random_forest': [\n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__n_estimators': [50, 100, 200]\n",
    "        }\n",
    "    ],\n",
    "    'decision_tree': [\n",
    "        {\n",
    "            'scaler': [StandardScaler(), MaxAbsScaler()],\n",
    "            'classifier__max_depth': [None, 5, 10]\n",
    "        }\n",
    "    ]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "66405de7-97f9-4989-a4a3-ed4d78a08d46",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "********** kneighbors **********\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024/03/27 09:57:12 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'toarray'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 5 folds for each of 54 candidates, totalling 270 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: \n",
      "180 fits failed out of a total of 270.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 578, in safe_patch_function\n",
      "    patch_function(call_original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 251, in patch_with_managed_run\n",
      "    result = patch_function(original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/sklearn/__init__.py\", line 1659, in patched_fit\n",
      "    return original(self, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 559, in call_original\n",
      "    return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 494, in call_original_fn_with_event_logging\n",
      "    original_fn_result = original_fn(*og_args, **og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 556, in _original_fn\n",
      "    original_result = original(*_og_args, **_og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "134 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "45 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 420, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/neighbors/_classification.py\", line 228, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 569, in _fit\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'minkowski' not valid for sparse input. Use sorted(sklearn.neighbors.VALID_METRICS_SPARSE['brute']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan 0.54793906        nan 0.58727143        nan        nan\n",
      "        nan 0.59699015        nan 0.61955369        nan        nan\n",
      "        nan 0.61077872        nan 0.63146297        nan        nan\n",
      "        nan 0.61908642        nan 0.63694739        nan        nan\n",
      "        nan 0.60404406        nan 0.62958148        nan        nan\n",
      "        nan 0.61046818        nan 0.6336561         nan        nan\n",
      "        nan 0.61062468        nan 0.63584886        nan        nan\n",
      "        nan 0.60592322        nan 0.63240145        nan        nan\n",
      "        nan 0.60670618        nan 0.6336561         nan        nan]\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the train scores are non-finite: [       nan 0.65849482        nan 0.69257364        nan        nan\n",
      "        nan 0.673887          nan 0.68285809        nan        nan\n",
      "        nan 0.65449726        nan 0.67298659        nan        nan\n",
      "        nan 0.64270606        nan 0.66914759        nan        nan\n",
      "        nan 0.63068025        nan 0.65531989        nan        nan\n",
      "        nan 0.63162069        nan 0.65285195        nan        nan\n",
      "        nan 0.62488291        nan 0.64873885        nan        nan\n",
      "        nan 0.62437409        nan 0.64572267        nan        nan\n",
      "        nan 0.6205351         nan 0.64294144        nan        nan]\n",
      "  warnings.warn(\n",
      "2024/03/27 10:00:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 5min 30s, sys: 4.59 s, total: 5min 34s\n",
      "Wall time: 3min 1s\n",
      "Train Score:  0.6369473909019719\n",
      "Test Score:  0.6226503759398496\n",
      "\n",
      "********** knn **********\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024/03/27 10:00:15 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'toarray'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 5 folds for each of 54 candidates, totalling 270 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: \n",
      "180 fits failed out of a total of 270.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 578, in safe_patch_function\n",
      "    patch_function(call_original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 251, in patch_with_managed_run\n",
      "    result = patch_function(original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/sklearn/__init__.py\", line 1659, in patched_fit\n",
      "    return original(self, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 559, in call_original\n",
      "    return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 494, in call_original_fn_with_event_logging\n",
      "    original_fn_result = original_fn(*og_args, **og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 556, in _original_fn\n",
      "    original_result = original(*_og_args, **_og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "134 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "45 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 420, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/neighbors/_classification.py\", line 228, in fit\n",
      "    return self._fit(X, y)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 569, in _fit\n",
      "    raise ValueError(\n",
      "ValueError: Metric 'minkowski' not valid for sparse input. Use sorted(sklearn.neighbors.VALID_METRICS_SPARSE['brute']) to get valid options. Metric can also be a callable function.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan 0.54793906        nan 0.58727143        nan        nan\n",
      "        nan 0.59699015        nan 0.61955369        nan        nan\n",
      "        nan 0.61077872        nan 0.63146297        nan        nan\n",
      "        nan 0.61908642        nan 0.63694739        nan        nan\n",
      "        nan 0.60404406        nan 0.62958148        nan        nan\n",
      "        nan 0.61046818        nan 0.6336561         nan        nan\n",
      "        nan 0.61062468        nan 0.63584886        nan        nan\n",
      "        nan 0.60592322        nan 0.63240145        nan        nan\n",
      "        nan 0.60670618        nan 0.6336561         nan        nan]\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the train scores are non-finite: [       nan 0.65849482        nan 0.69257364        nan        nan\n",
      "        nan 0.673887          nan 0.68285809        nan        nan\n",
      "        nan 0.65449726        nan 0.67298659        nan        nan\n",
      "        nan 0.64270606        nan 0.66914759        nan        nan\n",
      "        nan 0.63068025        nan 0.65531989        nan        nan\n",
      "        nan 0.63162069        nan 0.65285195        nan        nan\n",
      "        nan 0.62488291        nan 0.64873885        nan        nan\n",
      "        nan 0.62437409        nan 0.64572267        nan        nan\n",
      "        nan 0.6205351         nan 0.64294144        nan        nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 5min 27s, sys: 5.01 s, total: 5min 32s\n",
      "Wall time: 2min 54s\n",
      "Train Score:  0.6369473909019719\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024/03/27 10:03:10 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'toarray'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Test Score:  0.6226503759398496\n",
      "\n",
      "********** svc **********\n",
      "Fitting 5 folds for each of 60 candidates, totalling 300 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: \n",
      "150 fits failed out of a total of 300.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 578, in safe_patch_function\n",
      "    patch_function(call_original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 251, in patch_with_managed_run\n",
      "    result = patch_function(original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/sklearn/__init__.py\", line 1659, in patched_fit\n",
      "    return original(self, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 559, in call_original\n",
      "    return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 494, in call_original_fn_with_event_logging\n",
      "    original_fn_result = original_fn(*og_args, **og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 556, in _original_fn\n",
      "    original_result = original(*_og_args, **_og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "149 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan 0.60513976        nan 0.60012544        nan 0.64744687\n",
      "        nan 0.63663538        nan 0.63397167        nan 0.60184897\n",
      "        nan 0.60012544        nan 0.60012544        nan 0.60012544\n",
      "        nan 0.60012544        nan 0.60012544        nan 0.60012544\n",
      "        nan 0.60012544        nan 0.64102103        nan 0.61986754\n",
      "        nan 0.6129732         nan 0.60795973        nan 0.62770257\n",
      "        nan 0.61579525        nan 0.61438349        nan 0.61250347\n",
      "        nan 0.62409853        nan 0.61438471        nan 0.61407062\n",
      "        nan 0.61266058        nan 0.6461916         nan 0.60012544\n",
      "        nan 0.6485438         nan 0.62550968        nan 0.6048269 ]\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the train scores are non-finite: [       nan 0.60733311        nan 0.60012536        nan 0.77322945\n",
      "        nan 0.85024288        nan 0.85126138        nan 0.61281738\n",
      "        nan 0.63075847        nan 0.64885621        nan 0.66182221\n",
      "        nan 0.60012536        nan 0.60094798        nan 0.60717647\n",
      "        nan 0.6168913         nan 0.77879189        nan 0.77091823\n",
      "        nan 0.75940135        nan 0.751606          nan 0.84836261\n",
      "        nan 0.85036039        nan 0.84370102        nan 0.83543566\n",
      "        nan 0.85102635        nan 0.85126138        nan 0.85126138\n",
      "        nan 0.85126138        nan 0.66166566        nan 0.60012536\n",
      "        nan 0.78921195        nan 0.81322472        nan 0.81804303]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 11min 16s, sys: 8.21 s, total: 11min 24s\n",
      "Wall time: 11min 42s\n",
      "Train Score:  0.648543804911099\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024/03/27 10:14:53 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'toarray'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Test Score:  0.6320488721804511\n",
      "\n",
      "********** logistic_regression **********\n",
      "Fitting 5 folds for each of 30 candidates, totalling 150 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: \n",
      "75 fits failed out of a total of 150.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 578, in safe_patch_function\n",
      "    patch_function(call_original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 251, in patch_with_managed_run\n",
      "    result = patch_function(original, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/sklearn/__init__.py\", line 1659, in patched_fit\n",
      "    return original(self, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 559, in call_original\n",
      "    return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 494, in call_original_fn_with_event_logging\n",
      "    original_fn_result = original_fn(*og_args, **og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 556, in _original_fn\n",
      "    original_result = original(*_og_args, **_og_kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "74 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/mlflow/utils/autologging_utils/safety.py\", line 458, in safe_patch_function\n",
      "    return original(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 416, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 370, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/pipeline.py\", line 950, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/utils/_set_output.py\", line 140, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 918, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 837, in fit\n",
      "    return self.partial_fit(X, y, sample_weight)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/base.py\", line 1151, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "  File \"/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/preprocessing/_data.py\", line 901, in partial_fit\n",
      "    raise ValueError(\n",
      "ValueError: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan 0.63365671        nan 0.65606363        nan 0.6349099\n",
      "        nan 0.62942633        nan 0.6548107         nan 0.62926923\n",
      "        nan 0.62519546        nan 0.6253522         nan 0.62582255\n",
      "        nan 0.65857086        nan 0.6599809         nan 0.65888409\n",
      "        nan 0.63506725        nan 0.63475352        nan 0.63428355]\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the train scores are non-finite: [       nan 0.64901281        nan 0.75900975        nan 0.80946413\n",
      "        nan 0.63216844        nan 0.69245536        nan 0.80938588\n",
      "        nan 0.62817287        nan 0.62770284        nan 0.62797701\n",
      "        nan 0.72943442        nan 0.7227751         nan 0.71447046\n",
      "        nan 0.80938585        nan 0.80938584        nan 0.80903326]\n",
      "  warnings.warn(\n",
      "/Users/rameshbabu/miniconda3/envs/mlflow/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n",
      "2024/03/27 10:24:27 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'toarray'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 8min 31s, sys: 6.98 s, total: 8min 38s\n",
      "Wall time: 9min 33s\n",
      "Train Score:  0.6599809015546331\n",
      "Test Score:  0.6419172932330827\n",
      "\n",
      "********** random_forest **********\n",
      "Fitting 5 folds for each of 6 candidates, totalling 30 fits\n"
     ]
    }
   ],
   "source": [
    "best_models = {}\n",
    "\n",
    "# Run the Pipeline\n",
    "for algo in pipelines.keys():\n",
    "    print(\"*\"*10, algo, \"*\"*10)\n",
    "    grid_search = GridSearchCV(estimator=pipelines[algo], \n",
    "                               param_grid=param_grids[algo], \n",
    "                               cv=5, \n",
    "                               scoring='accuracy', \n",
    "                               return_train_score=True,\n",
    "                               verbose=1\n",
    "                              )\n",
    "    \n",
    "    mlflow.sklearn.autolog(max_tuning_runs=None)\n",
    "    \n",
    "    with mlflow.start_run() as run:\n",
    "        %time grid_search.fit(X_train, y_train)\n",
    "        \n",
    "    print('Train Score: ', grid_search.best_score_)\n",
    "    print('Test Score: ', grid_search.score(X_test, y_test))\n",
    "    \n",
    "    best_models[algo] = grid_search.best_estimator_\n",
    "    print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de808001-d7fe-42c4-a175-a4891aa832be",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28332af0-158f-4438-98ef-720f2252d3bb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
